manifest:
  remotes:
    # - name: zmkfirmware
    #   url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
    - name: zmk
      remote: badjeff
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-adns9800-driver
      remote: badjeff
      revision: main
    - name: zmk-behavior-key-tempo
      remote: badjeff
      revision: main
  self:
    path: config
